#!/bin/bash
# Run through README example options and settings

reset_options()
{
    echo "Resetting options."
    optionset ~nu air -q
    optionset ~functions on -q
    optionset ~density 1.225 -q
}

print_line()
{
    echo "############################################################"
}

request_keypress()
{
    echo
    print_line
    echo "Press any key to continue"
    print_line
    read -n 1 -s -r -p " "
}

print_line
reset_options
echo "View help with 'optionset -h'":
request_keypress
optionset -h
request_keypress

echo "The currently set options can be viewed with 'optionset'":
request_keypress
optionset
request_keypress

echo "To view what files these options are prescribed in, run 'optionset -f'":
request_keypress
optionset -f
request_keypress

echo "To set kinematic viscosity to that of water, run 'optionset ~nu water -v'":
request_keypress
optionset ~nu water -v
request_keypress

echo "To disable functions, run 'optionset ~functions off -v'":
request_keypress
optionset ~functions off -v
request_keypress

echo "To set density to that of water, run 'optionset ~density 1025 -v'":
request_keypress
optionset ~density 1025 -v
request_keypress

echo "To see all now-modified options and settings, run 'optionset'":
request_keypress
optionset
request_keypress

reset_options
