#!/bin/bash
# Run through README example options and settings

reset_options()
{
    echo "Resetting options."
    optionset.py ~nu air -q
    optionset.py ~functions on -q
    optionset.py ~density 1.225 -q
}

print_line()
{
    echo "############################################################"
}

request_keypress()
{
    echo
    print_line
    echo "Press any key to continue"
    print_line
    read -n 1 -s -r -p " "
}

print_line
reset_options
echo "View help with 'optionset.py -h'":
request_keypress
optionset.py -h
request_keypress

echo "The currently set options can be viewed with 'optionset.py -a'":
request_keypress
optionset.py -a
request_keypress

echo "To view what files these options are prescribed in, run 'optionset.py -a -f'":
request_keypress
optionset.py -a -f
request_keypress

echo "To set kinematic viscosity to that of water, run 'optionset.py ~nu water -v'":
request_keypress
optionset.py ~nu water -v
request_keypress

echo "To disable functions, run 'optionset.py ~functions off -v'":
request_keypress
optionset.py ~functions off -v
request_keypress

echo "To set density to that of water, run 'optionset.py ~density 1025 -v'":
request_keypress
optionset.py ~density 1025 -v
request_keypress

echo "To see all now-modified options and settings, run 'optionset.py -a'":
request_keypress
optionset.py -a
request_keypress

reset_options

